# Generated by Django 4.2.6 on 2023-10-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('instrument', models.CharField(choices=[('guitar', 'Guitar'), ('piano', 'Piano')], max_length=255, verbose_name='Instrument')),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('jazz', 'Jazz')], max_length=255, verbose_name='Genre')),
                ('users', models.ManyToManyField(blank=True, related_name='songs', to='music_app.user')),
            ],
        ),
    ]
