# Generated by Django 4.2.6 on 2023-11-11 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('instrument', models.CharField(choices=[('guitar', 'Guitar'), ('piano', 'Piano')], max_length=255, verbose_name='Instrument')),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('jazz', 'Jazz')], max_length=255, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('learned_songs', models.ManyToManyField(blank=True, related_name='learned_by', to='music_app.song')),
                ('liked_songs', models.ManyToManyField(blank=True, related_name='liked_by', to='music_app.song')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music_app.userprofile'),
        ),
    ]
