# Generated by Django 4.2.6 on 2023-11-23 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enjoyment', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music_app.song')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music_app.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'song')},
            },
        ),
    ]
