# Generated by Django 4.2.6 on 2023-11-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('rock', 'Rock'), ('jazz', 'Jazz'), ('pop', 'Pop'), ('hip_hop', 'Hip Hop'), ('edm', 'EDM'), ('classical', 'Classical'), ('country', 'Country'), ('blues', 'Blues'), ('rnb', 'R&B'), ('reggae', 'Reggae'), ('folk', 'Folk'), ('metal', 'Metal'), ('soul', 'Soul'), ('funk', 'Funk'), ('disco', 'Disco'), ('kpop', 'K-Pop'), ('alternative', 'Alternative'), ('indie', 'Indie'), ('dubstep', 'Dubstep'), ('ambient', 'Ambient'), ('instrumental', 'Instrumental'), ('acoustic', 'Acoustic'), ('soundtrack', 'Soundtrack')], max_length=255, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='instrument',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('drums', 'Drums'), ('violin', 'Violin'), ('flute', 'Flute'), ('cello', 'Cello')], max_length=255, verbose_name='Instrument'),
        ),
    ]
